apiVersion: v1
kind: Service
metadata:
  name: gym-application-service
spec:
  selector:
    app: gym-application
  type: ClusterIP
  ports:
    - name: gymapplication-service
      port: 3000
      targetPort: 3000
      protocol: TCP
